source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASDebugger_Example' do
    pod 'ASDebugger', :path => "../"
  pod 'AFNetworking', '3.1.0'
  pod 'ASIHTTPRequest', '1.8.2'
  pod 'SDWebImage', '3.8.2'
end

target 'ASDebugger_Tests' do
    pod 'ASDebugger', :path => "../"
end
